### ISSUE TITLE
Exception for Mattermost beta release versioning

### ISSUE THREAD

**Issue by SemaiCZE** [flathub/flatpak-builder-lint#101]
Hi,

I'd like to have an exception for [com.mattermost.Desktop](https://github.com/flathub/com.mattermost.Desktop/) on `beta` branch that is automatically released by the CI. Mattermost versioning scheme is like `5.2.1`, `5.2.2-rc.1`, `5.2.2-rc.2` and final `5.2.2` and this makes automatic PRs (https://github.com/flathub/com.mattermost.Desktop/pull/67) fail on `AppData problem: tag-invalid : <release> versions are not in order [5.2.2 before 5.2.2-rc.3]`.

Thank you.
-Petr

**Comment by hfiguiere** [comment]
this is not possible. it's appstream validation. They should fix this upstream.

**Comment by SemaiCZE** [comment]
@hfiguiere I'm sure they at Mattermost won't do anything to change their release schema, they are not much interested in flatpak. Can you elaborate more that the check is not possible to suppress? I tried to set https://github.com/flathub/com.mattermost.Desktop/blob/update-5218c69/flathub.json#L4, but it won't do anything. @vchernin suggested that exception in this repo should help. Can you please try? Something like [these lines](https://github.com/flathub/flatpak-builder-lint/blob/a765e58cbdee0964b69457d2d662879d99f48d3d/flatpak_builder_lint/staticfiles/exceptions.json#L1144-L1146) for Mattermost app?

**Comment by hfiguiere** [comment]
Except that appstream isn't flatpak specific. They violate the spec.

The solution here is to patch it when building the flatpak.

**Comment by SemaiCZE** [comment]
Yeah, but the `appdata.xml` file in Mattermost flathub repo is altered automaticaly by `flatpak-external-data-checker` tool. So this tool is broken? I didn't see any configuration option that can somehow change the release that is written to the appdata file.

**Comment by hfiguiere** [comment]
The thing is that since the appdata is actually in the flathub repo, you have total control of it. There is no reason for an exception.

**Comment by hfiguiere** [comment]
To be clear I didn't realise that was the case when I blamd upstream (which should manage it though, but that's a different matter)

**Comment by SemaiCZE** [comment]
Yes, appdata file is in the repo. But the problem is there is no place to update the version when `flatpak-external-data-checker` is running. I can imagine doing some `sed` work between clone and the tool, but it can change only old versions in appdata, not the RC one just being released.

For example, we have 5.2.1 and 5.2.2-rc.1. Before running external checker I guess I can update the 5.2.2-rc.1 to 5.2.2~rc1, but newly created PR will still have 5.2.2-rc.2. And when rc.3 is released, the previous -rc.2 gets changed to ~rc2 and so on. When stable version gets released all on the previous RC versions get changed so maybe it'll work, but it's not a nice solution in my opinion.

Or how would you do the modifications, @hfiguiere ? Can you sketch an update of my github workflow for automatic releasing new version in beta branch?

**Comment by vchernin** [comment]
A simpler hack could be to replace the appdata file with the one from master before flatpak-external-data-checker runs and adds a `rc` or stable version. So there would be at most one `rc` version at a time in the beta appdata file.

**Comment by SemaiCZE** [comment]
OK, I did one the hacks and seems to work for now. But I'm still not totally happy with that.
