### ISSUE TITLE
finish-args-contains-both-x11-and-fallback error is unnecessary

### ISSUE THREAD

**Issue by wjt** [flathub/flatpak-builder-lint#102]
`man flatpak build-finish` says:

> The `fallback-x11` option makes the X11 socket available only if there is no Wayland socket. This option was introduced
> in 0.11.3. To support older Flatpak releases, specify both `x11` and `fallback-x11`. The `fallback-x11` option takes
> precedence when both are supported.

So there is no harm in doing so. I slightly resent having to do the busywork of deleting a harmless line in every random old app I maintain, particularly when the Flatpak documentation actively recommends the opposite. (Admittedly only to support pre-1.0 versions of Flatpak, i.e. pre-Aug 20, 2018.)

If one were feeling really keen this error could be made conditional on the app's minimum required Flatpak version…

**Comment by Erick555** [comment]
Perhaps it could be a warning.

**Comment by hfiguiere** [comment]
> Perhaps it could be a warning.

no. it's an error.

wayland + x11 is a warning.

**Comment by hfiguiere** [comment]
> I slightly resent having to do the busywork of deleting a harmless line in every random old app I maintain,

You haven't maintained any software were one dependency change API and you need to fix it. This is life, and the linter is here to actually make things better in the future.

Also the present of `--socket=x11` make GNOME software say your package in not secure.

> particularly when the Flatpak documentation actively recommends the opposite. 

Please submit a PR to the documentation. Maybe we can get this part fixed too. It is full of obsolete stuff.

**Comment by wjt** [comment]
> > I slightly resent having to do the busywork of deleting a harmless line in every random old app I maintain,
> 
> You haven't maintained any software were one dependency change API and you need to fix it. 

I know you meant this rhetorically, but, yes, and it's annoying every time. It's even more annoying when the necessary fix has no functional impact! But I continue to work in software rather than moving off-grid and becoming a shepherd so I guess I've come to tolerate a certain background level of this stuff.

My point is that the linter is wrong to make this a fatal error: `--socket=x11 --socket=fallback-x11` and `--socket=fallback-x11` are equivalent. If you ignore the existence of pre-1.0 Flatpak, the latter is functionally identical, just tidier.

> Also the present of `--socket=x11` make GNOME software say your package in not secure.

GNOME Software correctly only flags the app as requiring X11 if `--socket=x11` is present AND `--socket=fallback-x11` is not present. [This special case, matching flatpak's handling of these flags, was added in GNOME 3.38.](https://gitlab.gnome.org/GNOME/gnome-software/-/commit/9b5e29b69084283acb922f185b656a93f454bf3b)

**Comment by barthalion** [comment]
I will make it a warning for now for backwards compatibility.
