### ISSUE TITLE
finish-args-arbitrary-dbus-access for Elisa

### ISSUE THREAD

**Issue by Pointedstick** [flathub/flatpak-builder-lint#120]
See: https://buildbot.flathub.org/#/builders/37/builds/2712

This is being proposed in https://github.com/flathub/org.kde.elisa/pull/89, because it's required for a feature of the app to work.

**Comment by hfiguiere** [comment]
no it shouldn't need this permission. You just need permission for the proper UDisk dbus name which doesn't require an exception.

**Comment by hfiguiere** [comment]
https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html

**Comment by Pointedstick** [comment]
Thanks, got it now.
