### ISSUE TITLE
What's the reason for the `appid-uses-code-hosting-domain` warning?

### ISSUE THREAD

**Issue by JakobDev** [flathub/flatpak-builder-lint#15]
I understand, that a Homepage should be used as App ID instead of the code hosting platform, if one exists. But many Apps did not have one, so they just use the code hoster as App ID. Why did this throw a warning? It's the only valid App ID in this cases. flatpak-builder-linter should never throw a warning (even if it is a warning and not a error) on a valid App ID.

**Comment by hfiguiere** [comment]
it should be `io.github` and not `com.github`. This is what the documentation says too.

**Comment by JakobDev** [comment]
`io.github` makes IMHO no sense, if the App has no page on github.io. And what should be the App ID for GitLab, where I (currently) host my code?

**Comment by barthalion** [comment]
GitLab.com uses gitlab.io for user-provided websites.

**Comment by sixpounder** [comment]
I am running into the same problem now that I am trying to push an update via pull request. Makes sense, yes, but the question I have is why then this did not popped up on the app submission test build?

What happens if I change the app id now? :)

**Comment by barthalion** [comment]
This might have been a bad timing with your submission, as I whitelisted almost all offending apps. Could you open a PR to https://github.com/flathub/flatpak-builder-lint/blob/master/flatpak_builder_lint/staticfiles/exceptions.json with the affected ID?

**Comment by sixpounder** [comment]
I can but I am already moving all internal namespaces from com.github.* to io.github.*. The only thing left unchanged is the name of the manifest itself.

If you tell me this is going to work there is no need to add an exception. If you see any problem(s) in this approach I'll revert and open the PR as you seuggested.

**Comment by barthalion** [comment]
The rename process requires resubmitting your application as the ID is tied to the repository name. You'll also need to migrate existing users with end-of-life and end-of-life-rebase as documented at https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life.

**Comment by barthalion** [comment]
Yes, this needs whitelisting either way.

**Comment by sixpounder** [comment]
PR opened as suggested. Thank you.
