### ISSUE TITLE
Add exception for io.github.Youda008.DoomRunner

### ISSUE THREAD

**Issue by mbugni** [flathub/flatpak-builder-lint#154]
Build for the new app [io.github.Youda008.DoomRunner](https://github.com/flathub/flathub/pull/4370) is failing due the ["finish-args-flatpak-spawn-access" error](https://github.com/flathub/flathub/pull/4370#issuecomment-1662961843).
Please add an exception.

For an explanation about reasons please take a look at [this comment](https://github.com/flathub/flathub/pull/4370#discussion_r1279884929).

**Comment by hfiguiere** [comment]
Fixed with #157
