### ISSUE TITLE
Make error message clear when `branch: stable` errors out in the manifest (fix: just remove  the line)

### ISSUE THREAD

**Issue by Jehan** [flathub/flatpak-builder-lint#202]
So I have this build: https://buildbot.flathub.org/#/builders/6/builds/80000 (for this pull request: https://github.com/flathub/org.gimp.GIMP/pull/265)

The builds themselves worked fine but the "Committing builds" failed with this error:

>    \ Check flathub-hooks has failed
>   Job failed: {'check_name': 'flathub-hooks', 'build_id': 62621, 'job_id': 99357, 'status': 3, 'status_reason': 'One or more validations failed.', 'results': '{"diagnostics":[{"refstring":"app/org.gimp.GIMP/aarch64/stable","is_warning":false,"category":"flatpak_builder_lint","data":{"stdout":{"errors":["flat-manager-branch-repo-mismatch"]},"stderr":""}},{"refstring":"app/org.gimp.GIMP/x86_64/stable","is_warning":false,"category":"flatpak_builder_lint","data":{"stdout":{"errors":["flat-manager-branch-repo-mismatch"]},"stderr":""}}]}'}

This error/check was apparently implemented just a few days ago: https://github.com/flathub/flatpak-builder-lint/commit/1544da3a86857e78ee7c8d438624a67c8ea74f2f

Looks like something to fix?

**Comment by hfiguiere** [comment]
I think it doesn't like "branch": "stable", in the manifest.

a test build is on the branch `test`.

**Comment by Jehan** [comment]
So now after testing, I think to understand the `branch` issue. In fact, the buildbot is overriding the branch name to be `test`, but the *real* build will still be `stable`, right? (or flatpak `beta` branch on the `beta` git branch respectively)

Cf. my comment: https://github.com/flathub/org.gimp.GIMP/pull/265#issuecomment-1803601336

If so, what about outputting a proper error message?

Something like:

> You must not set the branch name in your manifest and let Flathub's build bot override branch names. Test builds will be on flatpak branch `test`, stable builds on `stable` and beta builds on `beta`.

Or maybe something better worded, but you get the idea. At least the error is clear.

**Comment by bbhtt** [comment]
I posted a potential fix for this in https://github.com/flathub/flatpak-builder-lint/pull/215

**Comment by Erick555** [comment]
I don't think this needs fixing - hardcoding stable branch was mistake that makes testing more troublesome which was [acknowledged](https://github.com/flathub/org.gimp.GIMP/pull/265#issuecomment-1803601336).

**Comment by bbhtt** [comment]
I think the idea is not to force every app using "branch" to fail on that. But apps should move away from using it, yea

**Comment by Jehan** [comment]
Honestly I don't mind the failure if the error message is clear, making the fix obvious.
Also I really like that the test builds are installed as a `test` branch in flatpak. That makes complete sense and really help distinguish between test installs and official installs.

Though of course, your proposed idea is nice too. If flatpak-builder-lint is able to recognize known branch, but then I think it should also be able to rename the branch on the fly, because I still think that having the test builds as `test` flatpak branch should not be lost in the process. It's a real helper.

**Comment by bbhtt** [comment]
The linter acts on the final stage of the build when the refs are generated, while the branch override happens when the build is initiated with flatpak. I don't think it can override branches of already generated refs.

**Comment by Jehan** [comment]
> I don't know the history of using branch: stable but I don't think regular apps should be using it on Flathub because that's handled by build infra here. So the fix would be to remove it if you can.

That's what we already did. Cf. the link by @Erick555.

We don't have any problem anymore with this. I only left it opened for the "make a clear error" part now to help others who will have the issue. I edited the report title accordingly.

**Comment by Erick555** [comment]
> I think the idea is to not require apps removing that. There are a lot of apps already using it in their manifest on flathub

I think we agree they should remove it and linter error makes that happen.

**Comment by bbhtt** [comment]
This was pushed https://github.com/flathub/flatpak-builder-lint/commit/9c2a70dec9eeea08542155682ab2c2629cd6300a that should allow the ref branches (not test) to not error on the test repo. Meaning, apps on Flathub no longer need to remove `branch: stable` etc. from their manifest.

I think the documentation and the clearer error messages should be a separate issue, since they aren't related to this one error only.

**Comment by bbhtt** [comment]
I realised there are already docs for linter errors here https://docs.flathub.org/docs/for-app-authors/linter although outdated.

Here is a PR to include the current set of errors https://github.com/flathub/documentation/pull/125 which includes the branch-ref mismatch one.

**Comment by barthalion** [comment]
This should be resolved now via https://github.com/flathub/flatpak-builder-lint/commit/9c2a70dec9eeea08542155682ab2c2629cd6300a.

**Comment by bbhtt** [comment]
The error is not better documented at https://docs.flathub.org/docs/for-app-authors/linter#flat-manager-branch-repo-mismatch
