### ISSUE TITLE
XDG allowance for RetroDECK

### ISSUE THREAD

**Issue by XargonWan** [flathub/flatpak-builder-lint#208]
[Related build run](https://buildbot.flathub.org/#/builders/26/builds/10071)

```
flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions manifest net.retrodeck.retrodeck.yml
 in dir /srv/buildbot/worker/build-x86_64/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions manifest net.retrodeck.retrodeck.yml'
 using PTY: False
{
    "errors": [
        "finish-args-unnecessary-xdg-config-access"
    ]
}
program finished with exit code 1
elapsedTime=0.411195
```

I'm asking the allowance for RetroDECK because it's including CEMU that was allowed because of dark theme related fixes.

Refs:
[RetroDECK source manifest](https://github.com/XargonWan/RetroDECK/blob/355f357c40c685df1cc474932d426d857a0eff0c/net.retrodeck.retrodeck.yml#L1048)
[CEMU msnifest](https://github.com/flathub/info.cemu.Cemu/blob/093294145b789ff9ff33703ba3e3f506cb1aad82/info.cemu.Cemu.yml#L19)

**Comment by bbhtt** [comment]
The check got reverted in https://github.com/flathub/flatpak-builder-lint/pull/207, restart your builds after a few hours and it should work.

**Comment by XargonWan** [comment]
> The check got reverted in #207, restart your builds after a few hours and it should work.

Thanks

**Comment by XargonWan** [comment]
How can I restart that build?

**Comment by bbhtt** [comment]
bot, build on a PR or login to https://buildbot.flathub.org/#/builders/26/builds/10071 and hit start build

**Comment by XargonWan** [comment]
Thankyou
