### ISSUE TITLE
Build suddenly fails with jsonschema-validation-error

### ISSUE THREAD

**Issue by mfschumann** [flathub/flatpak-builder-lint#21]
I'm the maintainer of [eu.betterbird.Betterbird](https://github.com/flathub/eu.betterbird.Betterbird) and noticed that builds started to fail today because of the following error:
```
flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions eu.betterbird.Betterbird.json
 in dir /srv/buildbot/worker/build-x86_64-4/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions eu.betterbird.Betterbird.json'
 using PTY: False
{
    "errors": [
        "jsonschema-validation-error"
    ],
    "jsonschema": [
        "{'dest': 'cargo/vendor/atty-0.2.14', 'url': 'data:%7B%22package%22%3A%20%22d9b39be18770d11421cdb1b9947a45dd3f37e93092cbf377614828a319d5fee8%22%2C%20%22files%22%3A%20%7B%7D%7D', 'dest-filename': '.cargo-checksum.json', 'type': 'file'} is not valid under any of the given schemas"
    ]
}
```
The .json that causes the error used to work fine and I have not changed it, so I figured the linter must have changed.

@Erick555 FYI You should see the same behavior for org.mozilla.Thunderbird because you are using the same `cbindgen-sources.json` file. Can you confirm that?

**Comment by barthalion** [comment]
@mfschumann You need to recreate cbindgen-sources.json with the latest cargo generator from https://github.com/flatpak/flatpak-builder-tools.

**Comment by barthalion** [comment]
We try to announce breaking changes at our Discourse: https://discourse.flathub.org/c/announcements/6
