### ISSUE TITLE
finish-args-unnecessary-${xdg-dir}-access isn't always correct

### ISSUE THREAD

**Issue by TingPing** [flathub/flatpak-builder-lint#232]
The xdg-dir permissions are special. They do not only grant read access to a path they actually mount paths in different locations.

For example:

`--filesystem=home --filesystem=xdg-config/foo` will mount `~/.config/foo` to `~/.var/app/$FLATPAK_ID/config/foo`.

This is a valuable feature for applications that expect these in `$XDG_CONFIG_HOME`.

That said it is also often a misused feature. Flatpaks should rarely read host configs, that is usually a mistake. So I'd say it should only be done when that host data is required. I don't think it makes sense to load configs from the same app on the host (they are not necessarily compatible), nor does it make sense to load like gtk-3.0's settings.

So it is a valuable check but it does sometimes have valid usage.

**Comment by barthalion** [comment]
For apps actually using it correctly, we would accept an exception.

**Comment by hfiguiere** [comment]
> nor does it make sense to load like gtk-3.0's settings. 

This seem necessary for "bookmarks" in the file chooser.
