### ISSUE TITLE
`finish-args-unnecessary-xdg-data-access` error on calibre Flatpak

### ISSUE THREAD

**Issue by ghisvail** [flathub/flatpak-builder-lint#235]
A recent update to [calibre](https://github.com/flathub/com.calibre_ebook.calibre/pull/200) is triggering this error.

I have no idea what to do with this.

**Comment by hfiguiere** [comment]
Isn't this #233 ?

**Comment by ghisvail** [comment]
Probably, sorry for the noise. It was not obvious to me where to go from the error reported in the logs.

Looks like someone beat me to it.
