### ISSUE TITLE
Why does using plain cmake cause a warning?

### ISSUE THREAD

**Issue by kobus-v-schoor** [flathub/flatpak-builder-lint#26]
Hi there, I'm the maintainer of https://github.com/flathub/org.openhantek.OpenHantek6022 - I was doing some maintenance on it today and the build omitted the warning `module-openhantek-buildsystem-is-plain-cmake`. I'm trying to understand why this is a bad thing, as I can't find anything in the Flatpak docs saying I shouldn't be using cmake?

**Comment by hfiguiere** [comment]
we prefer `cmake-ninja` (it's way faster), except that sometime it doesn't work. It's just a warning.

**Comment by barthalion** [comment]
I'm behind with writing the documentation, but in the future, all warnings will have an explanation available.

**Comment by jonathon-love** [comment]
> I'm behind with writing the documentation, but in the future, all warnings will have an explanation available.

hi,

is it a bit premature to deploy a tool which blocks one's builds, without explanation for how to fix one's build? i appreciate the cmake one is just a warning, but i'm getting a `toplevel-cleanup-debug` error, and i've no idea why that's a problem.

with thanks

**Comment by hfiguiere** [comment]
> is it a bit premature to deploy a tool which blocks one's builds, without explanation for how to fix one's build? i appreciate the cmake one is just a warning, but i'm getting a `toplevel-cleanup-debug` error, and i've no idea why that's a problem.

That one is easy. `/lib/debug` is in the top level cleanup. It shoudln't be because it's used to build the Debug package. But that's not the original report either.

**Comment by hfiguiere** [comment]
There is documentation now
https://docs.flathub.org/docs/for-app-authors/linter/

**Comment by Erick555** [comment]
I don't see `buildsystem-is-plain-cmake` referenced in docs.

> we prefer `cmake-ninja` (it's way faster), except that sometime it doesn't work. It's just a warning.

cmake-ninja has big downside: it eats detailed build output which makes debugging impossible. For that reason I would drop the warning altogether.

**Comment by hfiguiere** [comment]
> I don't see buildsystem-is-plain-cmake referenced in docs.

PR welcome. the **errors** are documented at least up to before the latest version.

**Comment by Erick555** [comment]
Ok, but why close this issue which is about still undocumented **warning** then?

**Comment by bbhtt** [comment]
> Ok, but why close this issue which is about still undocumented **warning** then?

PR for warnings docs https://github.com/flathub/documentation/pull/141

**Comment by bbhtt** [comment]
Docs are live here https://docs.flathub.org/docs/for-app-authors/linter#linter-warnings I think there's nothing else to do here, so closing. If `cmake-ninja` doesn't work for some reason, keep it `cmake`, that's why it is a warning.
