### ISSUE TITLE
Question: Purpose of `flathub-json-modified-publish-delay`

### ISSUE THREAD

**Issue by p2004a** [flathub/flatpak-builder-lint#28]
`flathub-json-modified-publish-delay` started firing for repository I'm maintainer of but I can't find any explanation on why overriding `publish-delay-hours` below 3h is prohibited? And only if there aren't any `extra-data` sources?

Examples on documentation page https://github.com/flathub/flathub/wiki/App-Maintenance doesn't have any details and even example is about publishing more often.

**Comment by barthalion** [comment]
This setting has been introduced specifically for extra-data apps, which require faster publishing due to broken external URLs. It's not supposed to be modified by regular apps. I have removed it from the docs.

**Comment by p2004a** [comment]
What is the purpose of `publish-delay-hours` being >0 in general? Is it to protect flathub infrastructure? It adds additional latency for mitigating broken packages that were pushed to users with defects not found during testing.

**Comment by Erick555** [comment]
In case of emergency you can always login in https://buildbot.flathub.org and click one button to publish immediately.

**Comment by p2004a** [comment]
Ack, that's perfect, thank you!

**Comment by Pobega** [comment]
Is there any way to get an exception to this? I maintain com.fightcade.Fightcade which is a service application - when the client is out of date it can no longer connect to the service until Flathub serves the upgrade.

I've moved most of the heavy lifting into an extension so the main package builds in ~5 minutes, an additional three hours of being unable to connect is a bit irritating in this scenario.
