### ISSUE TITLE
Ignoring no commit or tag when shallow clone is disabled for git source ?

### ISSUE THREAD

**Issue by Lctrs** [flathub/flatpak-builder-lint#30]
In `flathub/net.rpcs3.RPCS3`, [we build a custom upstream fork of LLVM](https://github.com/flathub/net.rpcs3.RPCS3/blob/542ee91a5044053ab7b6b8cb4224139d92c41d17/net.rpcs3.RPCS3.yaml#L96) containing some specific patches for the application. As part of the build process, they are expecting the https://github.com/intel/ittapi repo to be cloned locally and are doing a git checkout of the expected version on it. So we need it to be fully cloned as part of the build process.

I was wondering if disabling this rule for git source that are not shallow cloned should be the default, as it's made to handle this type of build. Another alternative would be to add an exception for this repository.

**Comment by barthalion** [comment]
Do you mean that the build process checks out the proper commit in the repo?

**Comment by Lctrs** [comment]
Yes.

**Comment by Lctrs** [comment]
The proper tag to be more precise.

**Comment by barthalion** [comment]
Please submit a PR to the exceptions.json file. It sounds like an edge case not worth adding to the linter itself.
