### ISSUE TITLE
Easier local installation

### ISSUE THREAD

**Issue by kparal** [flathub/flatpak-builder-lint#32]
I'd like to run this tool locally so that I can attempt to fix its errors without constant pushes to Flathub git. I wonder if you could submit this tool to **PyPI**? That would make local installation easier than running it from a dev environment. Alternatively, for example [flatpak-external-data-checker](https://github.com/flathub/flatpak-external-data-checker) provides a flatpak-based installation, perhaps something like that would be an option here as well?

Thanks!

**Comment by barthalion** [comment]
It's available on org.flatpak.Builder (`flatpak run --command=flatpak-builder-lint org.flatpak.Builder`) or can be installed locally with `pip install git+https://github.com/flathub/flatpak-builder-lint`. I will look into publishing it to PyPI.

**Comment by kparal** [comment]
Great, thanks! It would be nice to put this info into the README file afterwards.

**Comment by kparal** [comment]
@hfiguiere Since this got closed, should I open a separate ticket for PyPI, or has the intention to submit this to PyPI been abandoned? Thanks.

**Comment by barthalion** [comment]
I think we won't be submitting it to PyPI at this point, given the dependency on specific versions of third-party tools and not upstreamed patches.
