### ISSUE TITLE
appid-code-hosting-too-few-components error backwards compatibility?

### ISSUE THREAD

**Issue by Eonfge** [flathub/flatpak-builder-lint#37]
Hey,

I recently ran into this linting issue;

```
{
    "errors": [
        "appid-code-hosting-too-few-components"
    ]
}
```

Not sure what to do now. Should the entire app be migrated to another domain, like `com.ezquake.ezQuake` or `com.github.QW-Group.ezQuake`?

**Comment by hfiguiere** [comment]
you need to submit an exception like https://github.com/flathub/flatpak-builder-lint/pull/25

**Comment by Eonfge** [comment]
See #38
