### ISSUE TITLE
cmake-no-debuginfo is bogus warning

### ISSUE THREAD

**Issue by Erick555** [flathub/flatpak-builder-lint#41]
Right now linter [checks](https://github.com/flathub/flatpak-builder-lint/blob/7db4a8b9b265fc3ac87f9980a571965f6b87f965/flatpak_builder_lint/checks/modules.py#L67) for `-DCMAKE_BUILD_TYPE=Release` and warns about supposedly missing debuginfo. This is misleading since cmake inherits `-g` from default `CFLAGS` environment which means `Release` has same amount of debuginfo as `RelWithDebInfo` has.

The actual difference is in optimization level `-O3` vs `-O2` which is different matter.

**Comment by hfiguiere** [comment]
In PR #50 I just change the test to **warn** is the build type isn't any of the know release one.
