### ISSUE TITLE
org.kde.kontact is suddenly unbuildable

### ISSUE THREAD

**Issue by tsdgeos** [flathub/flatpak-builder-lint#42]
flathub complains about

"finish-args-unnecessary-appid-own-name"

Please make it stop complaining about that :)

**Comment by hfiguiere** [comment]
remove the --own-name=org.kde.kontact from the manifest. it's implicit and that's the erro

**Comment by hfiguiere** [comment]
it's line 33

**Comment by hfiguiere** [comment]
and given that it forces QPA to be xcb, removing `"--socket=wayland",` would also help

**Comment by tsdgeos** [comment]
> it's implicit and that's the error

What's the rationale that made you decide that something that is implicit (and thus i understand not necessary to br set but not breaking either if it is set) to be a blocking build error? 

It's like if suddenly gcc decided to error in
  if (myBoolean == true)
because one should write
  if (myBoolean)

Seems like this should be at most a warning.

Sidenote this needs better documentation because i honestly read the code and thought the complain was about something else.

**Comment by hfiguiere** [comment]
A package is automatically granted to own its `app-id` DBus name.
