### ISSUE TITLE
module-{name}-cmake-non-release-build has too much false-positives

### ISSUE THREAD

**Issue by ilya-fedin** [flathub/flatpak-builder-lint#47]
It doesn't treat MinSizeRel and random values as release builds. The latter is actively used to prevent falling back to a project-defined default CMAKE_BUILD_TYPE and don't have additional C(XX)FLAGS set by cmake. The right way is check whether the value is Debug, that's also how most cmake projects check to insert their own debug flags.

**Comment by hfiguiere** [comment]
related to #41 

I think we should make it a warning (where `Release` and `RelWithDebInfo` are, and probably add `MinSizeRel` as an acceptable value too).

**Comment by ilya-fedin** [comment]
It checks for `--enable-debug` with autotools, why cmake is treated differently?

**Comment by hfiguiere** [comment]
In PR #50 I just change the test to **warn** is the build type isn't any of the know release one, including `MinSizeRel`

**Comment by hfiguiere** [comment]
> It checks for `--enable-debug` with autotools, why cmake is treated differently?

because cmake is different.

**Comment by ilya-fedin** [comment]
From my experience only `Debug` value is treated as debug, so it's not really different. It's a wide thing to set something like `-DCMAKE_BUILD_TYPE=None`.

**Comment by hfiguiere** [comment]
From the documentation these are arbitrary values that can lead ot arbitrary config. With some commonly in use.

This is also just a warning now as we can't really check how developers decided to mess with the CMake config.

**Comment by ilya-fedin** [comment]
Ok
