### ISSUE TITLE
jsonschema is not valid under any of the given schemas

### ISSUE THREAD

**Issue by Mailaender** [flathub/flatpak-builder-lint#58]
https://buildbot.flathub.org/#/builders/25/builds/262
> {
    "errors": [
        "jsonschema-validation-error"
    ],
    "warnings": [
        "module-allegro-buildsystem-is-plain-cmake"
    ],
    "jsonschema": [
        "{'dest': '.dub/packages', 'url': 'data:%5B%7B%22name%22%3A%20%22allegro%22%2C%20%22version%22%3A%20%224.0.4%2B5.2.0%22%2C%20%22path%22%3A%20%22%40builddir%40/.flatpak-dub/allegro-4.0.4%2B5.2.0%22%7D%2C%20%7B%22name%22%3A%20%22bolts%22%2C%20%22version%22%3A%20%221.3.1%22%2C%20%22path%22%3A%20%22%40builddir%40/.flatpak-dub/bolts-1.3.1%22%7D%2C%20%7B%22name%22%3A%20%22derelict-enet%22%2C%20%22version%22%3A%20%224.2.0%22%2C%20%22path%22%3A%20%22%40builddir%40/.flatpak-dub/derelict-enet-4.2.0%22%7D%2C%20%7B%22name%22%3A%20%22derelict-util%22%2C%20%22version%22%3A%20%223.0.0-beta.2%22%2C%20%22path%22%3A%20%22%40builddir%40/.flatpak-dub/derelict-util-3.0.0-beta.2%22%7D%2C%20%7B%22name%22%3A%20%22enumap%22%2C%20%22version%22%3A%20%220.4.2%22%2C%20%22path%22%3A%20%22%40builddir%40/.flatpak-dub/enumap-0.4.2%22%7D%2C%20%7B%22name%22%3A%20%22optional%22%2C%20%22version%22%3A%20%221.3.0%22%2C%20%22path%22%3A%20%22%40builddir%40/.flatpak-dub/optional-1.3.0%22%7D%2C%20%7B%22name%22%3A%20%22sdlang-d%22%2C%20%22version%22%3A%20%220.10.6%22%2C%20%22path%22%3A%20%22%40builddir%40/.flatpak-dub/sdlang-d-0.10.6%22%7D%2C%20%7B%22name%22%3A%20%22taggedalgebraic%22%2C%20%22version%22%3A%20%220.11.22%22%2C%20%22path%22%3A%20%22%40builddir%40/.flatpak-dub/taggedalgebraic-0.11.22%22%7D%2C%20%7B%22name%22%3A%20%22unit-threaded%22%2C%20%22version%22%3A%20%220.7.55%22%2C%20%22path%22%3A%20%22%40builddir%40/.flatpak-dub/unit-threaded-0.7.55%22%7D%5D', 'dest-filename': 'local-packages.json', 'type': 'file'} is not valid under any of the given schemas"
    ]
}

https://github.com/flathub/com.lixgame.Lix/pull/1 builds locally just fine. I don't understand this convoluted error message.

**Comment by hfiguiere** [comment]
Looks like the dub package list has `data:` URL. @gasinvein any idea?

**Comment by gasinvein** [comment]
This should be fixed in flatpak-builder-tools (please open an issue there), then sources can be regenreated with `inline` sources instead of `data:`.

**Comment by hfiguiere** [comment]
Closing this as the generator was fixed.
