### ISSUE TITLE
What is the "finish-args-arbitrary-xdg-config-access" problem?

### ISSUE THREAD

**Issue by rafatosta** [flathub/flatpak-builder-lint#87]
My app, [Zapzap](https://github.com/rafatosta/com.rtosta.zapzap), needs "--filesystem=xdg-config/autostart:create" to create the boot file.
I do not understand what the problem and how to fix it.
How to define this permission correctly?

**Comment by barthalion** [comment]
There's a background portal that allows to ask user if they want your app to be autostarted. You can poke around in the https://beta.flathub.org/apps/details/com.belmoussaoui.ashpd.demo source code or see https://github.com/mijorus/smile/commit/ea14de9784b6db2c67dccebfe64bab8efb881651 how it's used in Python.

**Comment by rafatosta** [comment]
> There's a background portal that allows to ask user if they want your app to be autostarted. You can poke around in the https://beta.flathub.org/apps/details/com.belmoussaoui.ashpd.demo source code or see [mijorus/smile@ea14de9](https://github.com/mijorus/smile/commit/ea14de9784b6db2c67dccebfe64bab8efb881651) how it's used in Python.

Thank you so much, I already made the correction in my application.
