### ISSUE TITLE
Extend xdg-* checks to catch subdirectories

### ISSUE THREAD

**Issue by barthalion** [flathub/flatpak-builder-lint#91]
As displayed by https://github.com/flathub/flathub/pull/3653/files#diff-7449d1d793006d078d8ec22550b1b85050f5dc864fb356154923fa08278ab3b8R18, we should probably lint any combination of xdg-* and subdirectories.

**Comment by hfiguiere** [comment]
we reverted #164 in #207

it triggered on runtime provided finish-args.
