### ISSUE TITLE
Allow git:// URLs

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/flatpak-builder-lint#98]
Is there a particular reason why git:// URLs are not allowed?

https://github.com/flathub/flatpak-builder-lint/blob/f04c0cef5db922fb872c915e28bfa58f5778f19f/flatpak_builder_lint/checks/modules.py#L43

This blocks e.g. this PR: https://github.com/flathub/io.qt.QtCreator/pull/89/files

**Comment by Erick555** [comment]
`git://` is unauthenticated use `https://` instead.

**Comment by hfiguiere** [comment]
And in that particular case: https://code.qt.io/cgit/qt/qtbase.git/ list the proper clone URL in https.

**Comment by Alexander-Wilms** [comment]
This would be covered by the documentation requested in #31
